// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9QB1lX5JsA84iWS-rDPVUrdsnCddt8TY',
    appId: '1:472478809847:web:3bfb508eaf04f783e1ddf2',
    messagingSenderId: '472478809847',
    projectId: 'verifyx-a78f5',
    authDomain: 'verifyx-a78f5.firebaseapp.com',
    databaseURL: 'https://verifyx-a78f5-default-rtdb.firebaseio.com',
    storageBucket: 'verifyx-a78f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbbs-oj1S8TbXQO1MURVNjf6HcU9xBqiQ',
    appId: '1:472478809847:android:a54c6418836daed0e1ddf2',
    messagingSenderId: '472478809847',
    projectId: 'verifyx-a78f5',
    databaseURL: 'https://verifyx-a78f5-default-rtdb.firebaseio.com',
    storageBucket: 'verifyx-a78f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxtKOWWrbR3tzQq10e7lNoPDB1pXAEQEA',
    appId: '1:472478809847:ios:65dfffc98dc3d542e1ddf2',
    messagingSenderId: '472478809847',
    projectId: 'verifyx-a78f5',
    databaseURL: 'https://verifyx-a78f5-default-rtdb.firebaseio.com',
    storageBucket: 'verifyx-a78f5.firebasestorage.app',
    iosClientId: '472478809847-6rltdnuqkc3ke35ug1n51uh2rqlj415j.apps.googleusercontent.com',
    iosBundleId: 'com.example.verifyx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxtKOWWrbR3tzQq10e7lNoPDB1pXAEQEA',
    appId: '1:472478809847:ios:65dfffc98dc3d542e1ddf2',
    messagingSenderId: '472478809847',
    projectId: 'verifyx-a78f5',
    databaseURL: 'https://verifyx-a78f5-default-rtdb.firebaseio.com',
    storageBucket: 'verifyx-a78f5.firebasestorage.app',
    iosClientId: '472478809847-6rltdnuqkc3ke35ug1n51uh2rqlj415j.apps.googleusercontent.com',
    iosBundleId: 'com.example.verifyx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9QB1lX5JsA84iWS-rDPVUrdsnCddt8TY',
    appId: '1:472478809847:web:e81239cfef31ffe1e1ddf2',
    messagingSenderId: '472478809847',
    projectId: 'verifyx-a78f5',
    authDomain: 'verifyx-a78f5.firebaseapp.com',
    databaseURL: 'https://verifyx-a78f5-default-rtdb.firebaseio.com',
    storageBucket: 'verifyx-a78f5.firebasestorage.app',
  );
}
